### ISSUE TITLE
Houdini 17 and 17.5 supported?

### ISSUE THREAD

**Issue by awesomez** [ttvd/houdini-geo-vox#1]
Just wondering if this binary works for Houdini 17 and/or 17.5 or not?

Will this be updated? -- If not, how would I do this in Houdini?

**Comment by ttvd** [comment]
Heya. I do not have H17, so I cannot tell you. You can try, it wouldn't hurt, but it probably will not work. You'd have to rebuild this node for H17.

**Comment by ttvd** [comment]
I can look into updating it, but it won't get to it for a while.

**Comment by awesomez** [comment]
Anything you'd be willing to do would help -- I have absolutely no idea how to approach extending Houdini with something like this. The file format seems pretty straightforward, but getting the full (unoptimized) geometry into Houdin seems impossible from any other approach at the moment.

MagicaVoxel is a great asset to Houdini due to its ease-of-use and its ability to quickly sketch out complex volumes that Houdini could tweak and work with procedurally. At some point in the near future I'm positive it could catch on as a legitimate workflow -- especially for games.
Houdini 17.5 added some interesting tools to deal with procedural tasks, and having access to a fast way to build 3d volumes to work with in Houdini would help in building larger, more complicated worlds/forms, so I would totally appreciate any efforts you'd be willing to put into this.

You rock. :)

**Comment by 6ecworks** [comment]
Any tips on how to get this to work for 17.5? )

**Comment by ttvd** [comment]
Hey guys, I updated the binary for 17.5.

@awesomez 
@6ecworks 

https://github.com/ttvd/houdini-geo-vox/releases/tag/1.0.4
